title: Paranoids
author: Paranoids
email: root@paranoids.info
description: >
  Paranoids - ресурс, специализирующийся на информационной безопасности.
  Цель проекта выходит далеко за рамки "приватного просмотра веб-страниц",
  и касается таких вопросов, как психология, навыки выживания в экстримальных ситуациях,
  построение телекоммуникационных сетей и их оптимизация, анонимизация в сети интернет и реальной жизни.
  Помимо этого проект является идеологическим родителем целого сообщества людей,  не равнодушных к тайне своей личной жизни.

baseurl: "/"
url: "https://paranoids.info"

telegram_username: paranoids_info
youtube_username: paranoidsinfo

collections:
  - setup

minimaless:
  date_format: "%Y-%m-%d %H:%M"
  
preview_posts: true
permalink: /:title
paginate: 5
paginate_path: "/page:num/"

header_pages:
  - _pages/blog.md
  - _pages/community.md
  - _pages/contact.md
  - _pages/services.md
  
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate

markdown: kramdown
theme: minimaless

include:
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
